HYDRA_FULL_ERROR=1 python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=data/gsm8k/train.parquet \
    data.val_files=data/gsm8k/test.parquet \
    data.train_batch_size=64 \
    data.val_batch_size=1 \
    data.max_prompt_length=512 \
    data.max_response_length=1500 \
    data.prompt_key=question \
    actor_rollout_ref.model.path=Qwen/Qwen2.5-0.5B \
    actor_rollout_ref.actor.optim.lr=1e-5 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=2048 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.0001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    ++actor_rollout_ref.actor.fsdp_config.model_dtype=bfloat16 \
    ++actor_rollout_ref.actor.fsdp_config.attn_implementation=flash_attention_2 \
    ++actor_rollout_ref.ref.fsdp_config.model_dtype=bfloat16 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=hf \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.9 \
    actor_rollout_ref.rollout.n=16 \
    actor_rollout_ref.rollout.dtype=bfloat16 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.0001 \
    reward_model.reward_manager=gsm8k_custom_v2 \
    trainer.critic_warmup=0 \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.logger=['console','tensorboard'] \
    trainer.val_before_train=False \
    trainer.save_freq=100 \
    trainer.test_freq=0 \
    trainer.total_epochs=5 \
    trainer.experiment_name=gsm8k-v6

    # trainer.total_training_steps=500 \
    # actor_rollout_ref.actor.ppo_mini_batch_size=4 \
    # ++actor_rollout_ref.actor.ppo_micro_batch_size=4 \
    # ++actor_rollout_ref.ref.log_prob_micro_batch_size=4 \
    # ++actor_rollout_ref.rollout.log_prob_micro_batch_size=4 \
    ##### -- FOR RESUMING -- 
    # trainer.resume_mode=resume_path \
    # trainer.resume_from_path=/path/to/parent/of/actor/